language: node_js
node_js:
 - "stable"
deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
install:
  - npm install -g serverless
  - travis_retry npm install
  - cd -
script:
  - npm test
  - sls deploy
  - cd -
environments:
  - &PRODUCTION_ENV
    - AWS_ACCESS_KEY_ID=AKIAQ7VZ4HU6JYL6724N
    - AWS_SECRET_ACCESS_KEY=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
  - &UAT_ENV
    - AWS_ACCESS_KEY_ID=AKIAQ7VZ4HU6BDFZRIIK
    - AWS_SECRET_ACCESS_KEY=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
  - &DEVELOPMENT_ENV
    - AWS_ACCESS_KEY_ID=AKIAQ7VZ4HU6ISBBHD5Y
    - AWS_SECRET_ACCESS_KEY=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
jobs:
  include:
    # develop branch deploys to the 'dev' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Users API"
      if: type = push AND branch = develop
      env:
        - SERVICE_PATH="users-api"
        - STAGE_NAME=dev
        - *DEVELOPMENT_ENV
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Test Experiences API"
      if: type = push AND branch = develop
      env:
        - SERVICE_PATH="todo-api"
        - STAGE_NAME=dev
        - *DEVELOPMENT_ENV
    # uat branch deploys to the 'uat' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Test Users API"
      if: type = push AND branch = uat
      env:
        - SERVICE_PATH="users-api"
        - STAGE_NAME=uat
        - *UAT_ENV
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Test Experiences API"
      if: type = push AND branch = uat
      env:
        - SERVICE_PATH="todo-api"
        - STAGE_NAME=uat
        - *UAT_ENV
    # master branch deploys to the 'prod' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Test Users API"
      if: type = push AND branch = master
      env:
        - SERVICE_PATH="users-api"
        - STAGE_NAME=prod
        - *PRODUCTION_ENV
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Test Experiences API"
      if: type = push AND branch = master
      env:
        - SERVICE_PATH="todo-api"
        - STAGE_NAME=prod
        - *PRODUCTION_ENV