language: node_js
node_js:
 - "stable"
deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ./resthub/node_modules
install:
  - npm install -g serverless
  - travis_retry npm install
  - cd ./resthub
  - travis_retry npm install
  - cd -
script:
  - cd ./resthub
  - npm test
  - sls deploy
  - cd -
environments:
  - &PRODUCTION_ENV
    - AWS_ACCESS_KEY_ID=${access}
    - AWS_SECRET_ACCESS_KEY=${secret}