language: node_js
node_js:
 - "stable"
deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
install:
  - npm install -g serverless
  - travis_retry npm install
script:
  - npm run test
  - sls deploy
  - cd -